# Используем легковесный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем необходимые файлы
COPY requirements.txt .
COPY app.py .
COPY instruction.txt .
COPY db.py .

# Установка зависимости openai определённой версии
RUN pip install --no-cache-dir openai==0.28.0

# Установка curl
RUN apt-get update && apt-get install -y curl

# Install dependencies, including sqlite3
RUN apt-get update && apt-get install -y --no-install-recommends \
    sqlite3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Инициализируем базу данных
RUN python db.py

# Открываем порт для Flask
EXPOSE 5000

# Команда для запуска приложения
CMD ["python", "app.py"]
